# Generated by Django 5.0.1 on 2024-03-10 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omega', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='vehicle_id',
            new_name='vehicle',
        ),
    ]
