# Generated by Django 5.0.1 on 2024-03-24 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omega', '0003_remove_reservation_reservation_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_vin', models.IntegerField()),
                ('vehicle_make', models.CharField(max_length=255)),
                ('vehicle_model', models.CharField(max_length=255)),
                ('vehicle_year', models.CharField(max_length=255)),
                ('vehicle_license_plate', models.CharField(max_length=255)),
                ('vehicle_color', models.CharField(max_length=255)),
                ('is_rented', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='reservation',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='omega.vehicle'),
        ),
        migrations.DeleteModel(
            name='vehicles',
        ),
    ]
