# Generated by Django 5.0.1 on 2024-03-25 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omega', '0004_vehicle_alter_reservation_vehicle_delete_vehicles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='additional_services',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='is_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='mileage_limit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='rental_period',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='drop_off_location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drop_off_location', to='omega.location'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='pick_up_location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pick_up_reservation', to='omega.location'),
        ),
    ]
