# Generated by Django 5.0.1 on 2024-04-09 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omega', '0011_alter_forumpost_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='parent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='omega.forumpost'),
        ),
    ]
